PDAF: comment out unused variables in solver_richards.c
Error:
```
parflow_pdaf/pfsimulator/parflow_lib/solver_richards.c:1817:16: error:
unused variable ‘pfl_start’ [-Werror=unused-variable]
```

Background: For PDAF, the subgrid-loops, where these variables are
originally used is commented out. However, up-to-now the (for PDAF)
unused variable were still declared.